### ISSUE TITLE
Recent go-ethereum update breaks ethconnect

### ISSUE THREAD

**Issue by Lsquared13** [kaleido-io/ethconnect#27]
A [recent commit to go-ethereum master](https://github.com/ethereum/go-ethereum/commit/7ca40306af9da68a0d31439117246de8247f99d6) breaks the version of ethconnect that `go get` fetches.

In particular the method signature to `abi.NewType` added a new argument [here](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/type.go#L66). Ethconnect still uses a single argument, [here for example](https://github.com/kaleido-io/ethconnect/blob/master/internal/kldeth/txn.go#L146).

This results in errors like the following:

```
# github.com/kaleido-io/ethconnect/internal/kldeth
/opt/transaction-executor/go/src/github.com/kaleido-io/ethconnect/internal/kldeth/txn.go:146:33: not enough arguments in call to abi.NewType
	have (string)
	want (string, []abi.ArgumentMarshaling)
/opt/transaction-executor/go/src/github.com/kaleido-io/ethconnect/internal/kldeth/txn.go:156:33: not enough arguments in call to abi.NewType
	have (string)
	want (string, []abi.ArgumentMarshaling)
/opt/transaction-executor/go/src/github.com/kaleido-io/ethconnect/internal/kldeth/txn.go:362:33: not enough arguments in call to abi.NewType
	have (string)
	want (string, []abi.ArgumentMarshaling)
```

**Comment by peterbroadhurst** [comment]
Thanks for raising this @Lsquared13 👍

**Comment by peterbroadhurst** [comment]
Investigating #27 I found that 1.8.21 of geth introduces a dependency on https://github.com/golang/go/issues/29533 which cannot be easily reconciled with standard Go versioning yet, as well as this new parameter.

So I've created branch [vgo](https://github.com/kaleido-io/ethconnect/compare/vgo) to swap the build to Go 1.11 and made it version aware, so we can pin to 1.8.20 for now.

However, I need to also reconcile a failure to install `solc` before Travis will build.

A related issue to be aware of is that solc is now at V0.5, which is unable to build V0.4 contracts. As such to avoid breaking the ability to deploy/run 0.4 contracts we need to make ethconnect version aware and be able to use multiple solc compilers. That's a side issue, but will affect anyone building ethconnect today - the build only works with solc 0.4.
